version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cvCollecter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-uxxq5pwc85g4"
s3_prefix = "cvCollecter"
region = "eu-west-3"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = true
image_repositories = []
